# FR3 Block Stacking 2024-09-16 50 Episodes (Downsampled)
# 对应 constants.py 中的 fr3_bs_0916_50ep_ds 配置

extends: base/fr3

task:
  name: fr3_ip_1105_41ep

data:
  dataset_dirs:
    - /data/fr3_hdf5/1105_insert_pinboard_3dmouse_41eps_hdf5
  episode_len: 300
  num_episodes: 41

training:
  ckpt_dir: ckpts/fr3_ip_1105_41ep
  batch_size: 64
  num_epochs: 8000
  lr: 5e-5
