# FR3 Mixed Training - 更强正则 + Dropout 调整
# 在 customcfg1 基础上引入 transformer dropout，并保留较小模型规模

extends: base/fr3

task:
  name: fr3_insert_tube

data:
  dataset_dirs:
    - /boot/common_data/2025/fr3_hdf5/1023_insert_tube_fr3_3dmouse_67ep_hdf5
  episode_len: 300

training:
  ckpt_dir: ckpts/fr3_it_1030_3dmouse_q2q_weight_decay
  batch_size: 8
  num_epochs: 8000
  lr: 1e-5

  kl_weight: 10
  chunk_size: 100
  hidden_dim: 512
  dim_feedforward: 3200
  dropout: 0.15
  weight_decay: 3e-4

  # lr_backbone: 0
  # position_embedding: sine
