# 数据增强配置
# 用于提高ACT模型对环境变化的鲁棒性

# 光照数据增强配置
lighting_augmentation:
  # 是否启用光照增强 (设为false可快速禁用)
  enabled: true

  # 颜色抖动参数 (取值范围 0-1)
  brightness: 0.2    # 亮度变化范围 ±30%
  contrast: 0.1      # 对比度变化范围 ±20%
  saturation: 0.1    # 饱和度变化范围 ±20%
  hue: 0.1          # 色调变化范围 ±10%

  # 自适应光照标准化
  adaptive_normalization: false
  target_mean: 0.5   # 目标亮度均值 (0-1)

# 相机角度增强配置（旋转）
rotation_augmentation:
  # 是否启用旋转增强 (设为false可快速禁用)
  enabled: true

  # 旋转角度范围（单位：度）
  max_rotation_degrees: 5.0  # 随机旋转 ±5度

  # 指定需要应用旋转的相机
  # 常见相机名称: third_person_cam, side_cam, ee_cam, top_cam
  target_cameras:
    - third_person_cam
    - side_cam

# 注意事项:
# 1. 增强只会应用到训练集，验证集保持原始
# 2. 如果发现训练损失上升，可以降低增强强度
# 3. 建议从较小的参数开始，逐步调优
# 4. 旋转增强主要用于模拟相机安装角度的微小变化
# 5. 对于end-effector相机(ee_cam)通常不建议应用旋转增强